"""add timestamp to emailcode

Revision ID: 074f18953c10
Revises: 685ad9ea4707
Create Date: 2024-01-03 00:39:20.436359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074f18953c10'
down_revision: Union[str, None] = '685ad9ea4707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_code', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('email_code', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('email_code', 'create_time')
    op.drop_column('email_code', 'expire_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_code', sa.Column('expire_time', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='expire_time'))
    op.add_column('email_code', sa.Column('create_time', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='create_time'))
    op.drop_column('email_code', 'updated_at')
    op.drop_column('email_code', 'created_at')
    # ### end Alembic commands ###
