"""add driver to user

Revision ID: 271b99d7aa5a
Revises: bb92632ed2f2
Create Date: 2024-01-03 00:28:53.135080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271b99d7aa5a'
down_revision: Union[str, None] = 'bb92632ed2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('drivers_user_id_fkey', 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'user_id')
    op.add_column('users', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'driver_id')
    op.add_column('drivers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('drivers_user_id_fkey', 'drivers', 'orders', ['user_id'], ['id'])
    # ### end Alembic commands ###
