"""init db

Revision ID: 357e58b58e1f
Revises: 0598fb49bf3a
Create Date: 2024-01-04 19:38:01.769777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357e58b58e1f'
down_revision: Union[str, None] = '0598fb49bf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('creator', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'warehouses', 'users', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'creator')
    # ### end Alembic commands ###
