"""make nullable order courier

Revision ID: 4389e48fa951
Revises: ff7f94a35b51
Create Date: 2024-01-06 04:25:52.248965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4389e48fa951'
down_revision: Union[str, None] = 'ff7f94a35b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'courier',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'courier',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
