"""init db

Revision ID: 58395014a4b7
Revises: c117fd7f0043
Create Date: 2024-01-04 22:12:03.200345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58395014a4b7'
down_revision: Union[str, None] = 'c117fd7f0043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('city', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'cities', ['city'], ['id'])
    op.add_column('warehouses', sa.Column('warehouse_user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'warehouses', 'users', ['warehouse_user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'warehouse_user')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'city')
    op.drop_column('users', 'salary')
    # ### end Alembic commands ###
