"""add driver

Revision ID: 59350e7572a8
Revises: 9732858cf610
Create Date: 2024-01-02 17:38:56.826684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59350e7572a8'
down_revision: Union[str, None] = '9732858cf610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('car_mark', sa.String(), nullable=False),
    sa.Column('car_plate_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=False),
    sa.Column('payer_type', sa.String(), nullable=False),
    sa.Column('bin', sa.String(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('courier', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('sender', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('reciever', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('order_status', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('total_weight', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('total_volume', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'orders', 'users', ['sender'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['reciever'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['courier'], ['id'])
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'total_volume')
    op.drop_column('orders', 'total_weight')
    op.drop_column('orders', 'order_status')
    op.drop_column('orders', 'reciever')
    op.drop_column('orders', 'sender')
    op.drop_column('orders', 'courier')
    op.drop_table('payments')
    op.drop_table('order_items')
    op.drop_table('drivers')
    # ### end Alembic commands ###
