"""add direction_id

Revision ID: 75650812e9c5
Revises: 870a594c461f
Create Date: 2024-01-08 01:20:29.289678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75650812e9c5'
down_revision: Union[str, None] = '870a594c461f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('direction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'directions', ['direction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'direction_id')
    # ### end Alembic commands ###
