"""add direction

Revision ID: 7e5fd227ecc3
Revises: feb83b05319e
Create Date: 2024-01-06 04:58:40.703003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e5fd227ecc3'
down_revision: Union[str, None] = 'feb83b05319e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arrival_city_id', sa.Integer(), nullable=False),
    sa.Column('departure_city_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('transportation_type', postgresql.ENUM('AIR', 'SEA', 'RAIL', 'ROAD', name='transportationtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['arrival_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['departure_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('directions')
    # ### end Alembic commands ###
