"""change field

Revision ID: 857907ee9712
Revises: e86bfeed5251
Create Date: 2023-12-21 10:00:31.835119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857907ee9712'
down_revision: Union[str, None] = 'e86bfeed5251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('creator', sa.Integer(), nullable=False))
    op.drop_constraint('orders_creator_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['creator'], ['id'])
    op.drop_column('orders', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_creator_id_fkey', 'orders', 'users', ['creator_id'], ['id'])
    op.drop_column('orders', 'creator')
    # ### end Alembic commands ###
