"""add group_id to permission

Revision ID: 870a594c461f
Revises: 7e5fd227ecc3
Create Date: 2024-01-07 19:18:58.723934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870a594c461f'
down_revision: Union[str, None] = '7e5fd227ecc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fastapi_auth_permission', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fastapi_auth_permission', 'fastapi_auth_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fastapi_auth_permission', type_='foreignkey')
    op.drop_column('fastapi_auth_permission', 'group_id')
    # ### end Alembic commands ###
