"""init new data

Revision ID: 9339f62334c3
Revises: 58395014a4b7
Create Date: 2024-01-04 22:37:33.408783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9339f62334c3'
down_revision: Union[str, None] = '58395014a4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('creator', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'creator')
    # ### end Alembic commands ###
