"""init db

Revision ID: 954e2bce12e6
Revises: 
Create Date: 2024-01-03 10:20:41.596764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954e2bce12e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('car_mark', sa.String(), nullable=False),
    sa.Column('car_plate_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fastapi_auth_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True, comment='group name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_auth_group_id'), 'fastapi_auth_group', ['id'], unique=False)
    op.create_index(op.f('ix_fastapi_auth_group_name'), 'fastapi_auth_group', ['name'], unique=True)
    op.create_table('fastapi_auth_permission',
    sa.Column('name', sa.String(length=128), nullable=True, comment='Permission Name'),
    sa.Column('codename', sa.String(length=100), nullable=False, comment='Permission Field'),
    sa.PrimaryKeyConstraint('codename')
    )
    op.create_index(op.f('ix_fastapi_auth_permission_name'), 'fastapi_auth_permission', ['name'], unique=True)
    op.create_table('fastapi_auth_group_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('codename', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['codename'], ['fastapi_auth_permission.codename'], ),
    sa.ForeignKeyConstraint(['group_id'], ['fastapi_auth_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'codename', name='idx_group_id_permission_id')
    )
    op.create_index(op.f('ix_fastapi_auth_group_permission_id'), 'fastapi_auth_group_permission', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=True, comment='Are you a super administrator'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True, comment='Whether to engrave to log in'),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=True, comment='delete or not'),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['fastapi_auth_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False, comment='email'),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False, comment='code'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_code_id'), 'email_code', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('courier', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=False),
    sa.Column('reciever', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=False),
    sa.Column('total_volume', sa.Float(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courier'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reciever'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=False),
    sa.Column('payer_type', sa.String(), nullable=False),
    sa.Column('bin', sa.String(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_index(op.f('ix_email_code_id'), table_name='email_code')
    op.drop_table('email_code')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fastapi_auth_group_permission_id'), table_name='fastapi_auth_group_permission')
    op.drop_table('fastapi_auth_group_permission')
    op.drop_index(op.f('ix_fastapi_auth_permission_name'), table_name='fastapi_auth_permission')
    op.drop_table('fastapi_auth_permission')
    op.drop_index(op.f('ix_fastapi_auth_group_name'), table_name='fastapi_auth_group')
    op.drop_index(op.f('ix_fastapi_auth_group_id'), table_name='fastapi_auth_group')
    op.drop_table('fastapi_auth_group')
    op.drop_table('drivers')
    op.drop_table('cities')
    # ### end Alembic commands ###
