"""new models

Revision ID: 9732858cf610
Revises: d745c57c0621
Create Date: 2023-12-29 16:43:31.430374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9732858cf610'
down_revision: Union[str, None] = 'd745c57c0621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fastapi_auth_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True, comment='group name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fastapi_auth_group_id'), 'fastapi_auth_group', ['id'], unique=False)
    op.create_index(op.f('ix_fastapi_auth_group_name'), 'fastapi_auth_group', ['name'], unique=True)
    op.create_table('fastapi_auth_permission',
    sa.Column('name', sa.String(length=128), nullable=True, comment='Permission Name'),
    sa.Column('codename', sa.String(length=100), nullable=False, comment='Permission Field'),
    sa.PrimaryKeyConstraint('codename')
    )
    op.create_index(op.f('ix_fastapi_auth_permission_name'), 'fastapi_auth_permission', ['name'], unique=True)
    op.create_table('fastapi_auth_group_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('codename', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['codename'], ['fastapi_auth_permission.codename'], ),
    sa.ForeignKeyConstraint(['group_id'], ['fastapi_auth_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'codename', name='idx_group_id_permission_id')
    )
    op.create_index(op.f('ix_fastapi_auth_group_permission_id'), 'fastapi_auth_group_permission', ['id'], unique=False)
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=True, comment='Are you a super administrator'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True, comment='Whether to engrave to log in'))
    op.add_column('users', sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=True, comment='delete or not'))
    op.add_column('users', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'fastapi_auth_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'group_id')
    op.drop_column('users', 'is_delete')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_superuser')
    op.drop_index(op.f('ix_fastapi_auth_group_permission_id'), table_name='fastapi_auth_group_permission')
    op.drop_table('fastapi_auth_group_permission')
    op.drop_index(op.f('ix_fastapi_auth_permission_name'), table_name='fastapi_auth_permission')
    op.drop_table('fastapi_auth_permission')
    op.drop_index(op.f('ix_fastapi_auth_group_name'), table_name='fastapi_auth_group')
    op.drop_index(op.f('ix_fastapi_auth_group_id'), table_name='fastapi_auth_group')
    op.drop_table('fastapi_auth_group')
    # ### end Alembic commands ###
