"""direction_id Optional

Revision ID: e58ef216776d
Revises: 75650812e9c5
Create Date: 2024-01-09 20:04:28.279380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58ef216776d'
down_revision: Union[str, None] = '75650812e9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
