"""remove warehouse user

Revision ID: feb83b05319e
Revises: 4389e48fa951
Create Date: 2024-01-06 04:31:29.905209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb83b05319e'
down_revision: Union[str, None] = '4389e48fa951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('warehouses_warehouse_user_fkey', 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'warehouse_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('warehouse_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('warehouses_warehouse_user_fkey', 'warehouses', 'users', ['warehouse_user'], ['id'])
    # ### end Alembic commands ###
